from tkinter import *
from tkinter import messagebox
root = Tk()
root.title("CATS")
root.geometry("400x800")
root.resizable(width=True,height=True)
root.configure(bg="snow")
root.grid_columnconfigure(0,minsize = 50)
root.grid_rowconfigure(1,minsize = 50)
frame1 = Frame(root,width = 400,height = 100,bg = "white")
frame1.pack()
label1 = Label(frame1,text = "Name")
label1.place(x = 50, y = 40)
label2 = Label(frame1,text = "Number")
label2.place(x = 50, y = 70)
box1 = Entry(frame1,text = "")
box1.place(x = 120,y = 40)
box2 = Entry(frame1,text = "")
box2.place(x = 120,y = 70)

frame2 = Frame(root,width = 400,height = 25,bg = "white")
frame2.pack()
button1 = Button(frame2, text = "Add",width = 10)
button1.place(x=0,y = 0)
button2 = Button(frame2, text = "Update",width = 10)
button2.place(x=100,y = 0)
button3 = Button(frame2, text = "Delete",width = 10)
button3.place(x=200,y = 0)
button4 = Button(frame2, text = "See",width = 10)
button4.place(x=300,y = 0)

frame3 = Frame(root,width = 400, height= 675)
frame3.pack()
scroll = Scrollbar(frame3,orient = VERTICAL)
scroll.pack(side = RIGHT,fill = Y)
contacts = Listbox(frame3,yscrollcommand = scroll.set,height = 10)
contacts.pack(side = LEFT)
scroll.config(command = select.yview)


root.mainloop()
