from tkinter import *
from tkinter import messagebox
root = Tk()
root.title("CATS")
root.geometry("900x900")
root.resizable(width=True,height=True)
root.configure(bg="snow")
root.grid_columnconfigure(0,minsize = 50)
root.grid_rowconfigure(1,minsize = 50)
a = PhotoImage(file = "america.png")
b = PhotoImage(file = "download-1.png")
c = PhotoImage(file = "russia.png")
frame1 = Frame(root,width = "1000",height = "300",background = "blue")
button1 = Button(frame1,text = "amarica",command = "AM")
button1.grid(row = 1,column = 1,padx = 10,pady = 2)
Label1 = Label(frame1,image = a)
frame1.pack()
frame2 = Frame(root,width = "1000",height = "300",background = "red")
button2 = Button(frame2,text = "canada",command = "CA")
Label2 = Label(frame2,image = a)
frame2.pack()
frame3 = Frame(root,width = "1000",height = "300",background = "pink")
button3 = Button(frame2,text = "russia",command = "RA")
Label3 = Label(frame3,image = a)
frame3.pack()
root.mainloop()
