from tkinter import *
from tkinter import messagebox
root = Tk()
root.title("CATS")
root.geometry("1000x500")
root.resizable(width=True,height=True)
root.configure(bg="black")
root.grid_columnconfigure(0,minsize = 50)
root.grid_rowconfigure(1,minsize = 50)
a = IntVar()
b = IntVar()
lable1 = Label(root,text = "find",width = 10, height = 1)
lable1.grid(row = 10,column = 1,padx = 2,pady = 10)
lable2 = Label(root,text = "replace",width = 10, height = 1)
lable2.grid(row = 12,column = 1,padx = 2,pady = 10)
box1 = Entry(root,text = "",width = 70)
box1.grid(row = 10, column = 2,padx = 20,columnspan = 3)
box2 = Entry(root,text = "",width = 70)
box2.grid(row = 12, column = 2,padx = 20,columnspan = 3)
check1 = Checkbutton(root,text = "match whole word only",width = 20, height = 2)
check1.grid(row = 14,column = 2,pady = 20,sticky = W, padx = 20)
check2 = Checkbutton(root,text = "match case",width = 20, height = 2)
check2.grid(row = 15,column = 2,pady = 20,sticky = W, padx = 20)
check3 = Checkbutton(root,text = "wrap around",width = 20, height = 2)
check3.grid(row = 16,column = 2,pady = 20,sticky = W, padx = 20)
button1 = Button(root,text = "find",width = 10, height = 1)
button1.grid(row = 11,column = 5,padx = 5, pady = 5)
button2 = Button(root,text = "find all",width = 10, height = 1)
button2.grid(row = 12,column = 5,padx = 5, pady = 5)
button3 = Button(root,text = "replace",width = 10, height = 1)
button3.grid(row = 13,column = 5,padx = 5, pady = 5)
button4 = Button(root,text = "replace all",width = 10, height = 1)
button4.grid(row = 14,column = 5,padx = 5, pady = 5)
lable3 = Label(root,text = "direction",width = 10, height = 2)
lable3.grid(row = 14,column = 3)
radio1 = Radiobutton(root,text = "up",width = 20, height = 2,variable = a)
radio1.grid(row = 15, column = 3)
radio2 = Radiobutton(root,text = "down",width = 20, height = 2,variable = b)
radio2.grid(row = 15, column = 4)
root.mainloop()
